INSERT INTO REVIEW VALUES(1,'IT IS A SAFE FALLBACK POINT', 0);
INSERT INTO REVIEW VALUES(2,'IT IS A GOOD PEN', 1);
INSERT INTO REVIEW VALUES(3,'IT IS A GREAT PEN', 1);
INSERT INTO REVIEW VALUES(4,'IT IS A GOOD TOOTHBRUSH', 2);
INSERT INTO REVIEW VALUES(5,'IT IS A GREAT TOOTHBRUSH', 2);
